import os
import json

YOUTUBE_CHANNELS = [
    # "UCn8ujwUInbJkBhffxqAPBVQ", # Dave Ebbelaar
    "UCawZsQWqfGSbCI5yjkdVkTA", # Matthew Berman
]

STORY_MATCHING_WINDOW_HOURS = 48
STORY_MATCHING_HIGH_THRESHOLD = 0.75
STORY_MATCHING_LOW_THRESHOLD = 0.35
ENRICHMENT_MODEL = os.getenv("ENRICHMENT_MODEL", "gpt-4o-mini")
ENRICHMENT_PROMPT_VERSION = os.getenv("ENRICHMENT_PROMPT_VERSION", "v1")
ENRICHMENT_MAX_CONTENT_CHARS = int(os.getenv("ENRICHMENT_MAX_CONTENT_CHARS", "12000"))
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "text-embedding-3-small")
EMBEDDING_DIMENSIONS = int(os.getenv("EMBEDDING_DIMENSIONS", "1536"))
EMBEDDING_BATCH_SIZE = int(os.getenv("EMBEDDING_BATCH_SIZE", "32"))
EMBEDDING_MAX_CONTENT_CHARS = int(os.getenv("EMBEDDING_MAX_CONTENT_CHARS", "12000"))
RAG_MODEL = os.getenv("RAG_MODEL", ENRICHMENT_MODEL)
RAG_MAX_CONTEXT_ITEMS = int(os.getenv("RAG_MAX_CONTEXT_ITEMS", "8"))
RAG_MAX_CONTEXT_CHARS = int(os.getenv("RAG_MAX_CONTEXT_CHARS", "12000"))
RANKING_SEMANTIC_WEIGHT = float(os.getenv("RANKING_SEMANTIC_WEIGHT", "0.40"))
RANKING_TOPIC_WEIGHT = float(os.getenv("RANKING_TOPIC_WEIGHT", "0.20"))
RANKING_ENTITY_WEIGHT = float(os.getenv("RANKING_ENTITY_WEIGHT", "0.15"))
RANKING_FRESHNESS_WEIGHT = float(os.getenv("RANKING_FRESHNESS_WEIGHT", "0.15"))
RANKING_SOURCE_WEIGHT = float(os.getenv("RANKING_SOURCE_WEIGHT", "0.10"))
RANKING_EXCLUSION_PENALTY = float(os.getenv("RANKING_EXCLUSION_PENALTY", "1.0"))
RANKING_FRESHNESS_HALF_LIFE_DAYS = float(
    os.getenv("RANKING_FRESHNESS_HALF_LIFE_DAYS", "7")
)
try:
    RANKING_SOURCE_QUALITY = json.loads(
        os.getenv("RANKING_SOURCE_QUALITY", "{}")
    )
except json.JSONDecodeError:
    RANKING_SOURCE_QUALITY = {}
TREND_RECENT_DAYS = int(os.getenv("TREND_RECENT_DAYS", "7"))
TREND_PREVIOUS_DAYS = int(os.getenv("TREND_PREVIOUS_DAYS", "7"))
TREND_MIN_RECENT_CONTENT = int(os.getenv("TREND_MIN_RECENT_CONTENT", "2"))
TREND_MIN_RECENT_STORIES = int(os.getenv("TREND_MIN_RECENT_STORIES", "1"))
TREND_GROWTH_WEIGHT = float(os.getenv("TREND_GROWTH_WEIGHT", "0.35"))
TREND_ACTIVITY_WEIGHT = float(os.getenv("TREND_ACTIVITY_WEIGHT", "0.20"))
TREND_STORY_DIVERSITY_WEIGHT = float(os.getenv("TREND_STORY_DIVERSITY_WEIGHT", "0.20"))
TREND_SOURCE_DIVERSITY_WEIGHT = float(os.getenv("TREND_SOURCE_DIVERSITY_WEIGHT", "0.15"))
TREND_RECENCY_WEIGHT = float(os.getenv("TREND_RECENCY_WEIGHT", "0.10"))
TREND_EMERGING_THRESHOLD = float(os.getenv("TREND_EMERGING_THRESHOLD", "0.55"))
API_VERSION = os.getenv("API_VERSION", "0.1.0")
API_CORS_ORIGINS = [
    value.strip() for value in os.getenv(
        "API_CORS_ORIGINS", "http://localhost:3000"
    ).split(",") if value.strip()
]
