import os

YOUTUBE_CHANNELS = [
    # "UCn8ujwUInbJkBhffxqAPBVQ", # Dave Ebbelaar
    "UCawZsQWqfGSbCI5yjkdVkTA", # Matthew Berman
]

STORY_MATCHING_WINDOW_HOURS = 48
STORY_MATCHING_HIGH_THRESHOLD = 0.75
STORY_MATCHING_LOW_THRESHOLD = 0.35
ENRICHMENT_MODEL = os.getenv("ENRICHMENT_MODEL", "gpt-4o-mini")
ENRICHMENT_PROMPT_VERSION = os.getenv("ENRICHMENT_PROMPT_VERSION", "v1")
ENRICHMENT_MAX_CONTENT_CHARS = int(os.getenv("ENRICHMENT_MAX_CONTENT_CHARS", "12000"))
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "text-embedding-3-small")
EMBEDDING_DIMENSIONS = int(os.getenv("EMBEDDING_DIMENSIONS", "1536"))
EMBEDDING_BATCH_SIZE = int(os.getenv("EMBEDDING_BATCH_SIZE", "32"))
EMBEDDING_MAX_CONTENT_CHARS = int(os.getenv("EMBEDDING_MAX_CONTENT_CHARS", "12000"))
RAG_MODEL = os.getenv("RAG_MODEL", ENRICHMENT_MODEL)
RAG_MAX_CONTEXT_ITEMS = int(os.getenv("RAG_MAX_CONTEXT_ITEMS", "8"))
RAG_MAX_CONTEXT_CHARS = int(os.getenv("RAG_MAX_CONTEXT_CHARS", "12000"))
